name: Event Template
description: Event form template 
title: "[Event]: "
labels: ["event", "new"]
projects: ["Events"]
assignees:
  - congiuluc
body:
  - type: markdown
    attributes:
      value: |
        Please insert here your event
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. username
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description:
      placeholder: Event description 
      value: ""
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Event type
      description: Is your event in person, online or hybrid
      options:
        - In Person
        - Online
        - Hybrid
      default: 0
    validations:
      required: true
  - type: input
    id: eventimage
    attributes:
      label: Image event url
      description: 
      placeholder: https://
    validations:
      required: true
  - type: input
    id: website
    attributes:
      label: Website url
      description: 
      placeholder: https://
    validations:
      required: true
  - type: input
    id: registration
    attributes:
      label: Registration url
      description: 
      placeholder: https://
    validations:
      required: false
  - type: input
    id: call-for-paper
    attributes:
      label: Call for paper url
      description: 
      placeholder: https://
    validations:
      required: false
 
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
