           
name: ISSUE_CI
on:
  issues:
    types: [opened, edited, closed]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world! ${{ github.event.issue.number }} 

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build ${{ github.event.issue.title }},
          echo test, and deploy your project ${{ github.event.issue.contact }}.

      - name: Create JSON File
        run: |
          echo '{
            "name": "John Doe",
            "email": "john.doe@example.com"
          }' > example.json

      - name: Commit JSON file
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add example.json
          git commit -m "Add JSON file"
          git push
